### ISSUE TITLE
Transparent layout subwindow

### ISSUE THREAD

**Issue by farseerfc** [fcitx/kcm-fcitx5#4]
In kcm-fcitx5 , click layout button for a input method, the layout subwindow appear to be transparent:
![image](https://user-images.githubusercontent.com/861563/82866292-934b8480-9f63-11ea-9afd-1b9c3bf67955.png)

Is this an issue of kcm-fcitx5 ?

**Comment by wengxt** [comment]
looks like the issue is related to your style? can you check if same happens with kirigami-gallery?
