### ISSUE TITLE
可否考虑让 kcm 设置的背景遵循默认背景？

### ISSUE THREAD

**Issue by cathaysia** [fcitx/kcm-fcitx5#7]
我现在 kde 设置的主题是 https://github.com/vinceliuice/WhiteSur-kde 
这个主题大量使用了透明元素，导致 kcm 里背景可以看到一条透明边。如图：

![图片](https://user-images.githubusercontent.com/42114817/89091830-4a8ace80-d3df-11ea-8a8b-bb5b515ca4e9.png)

而在另外一些设置中，似乎使用了系统默认的背景色：

![图片](https://user-images.githubusercontent.com/42114817/89091845-6d1ce780-d3df-11ea-8e1f-648f1fe39c84.png)
![图片](https://user-images.githubusercontent.com/42114817/89091848-760db900-d3df-11ea-8075-dbedb84b47a6.png)

**Comment by wengxt** [comment]
我觉得没什么希望，建议你对比一下比如配置颜色的 kcm，都是 qml 写的。可能也没有这种背景。
他们的主题不走 qwidget
